# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 872aa30aae8fde66126ae8691d75bc7322e165f739e56d07c16e839f3e348b0b8bea1523b6401881401bf115b14fdba85215478cde58f49a1a2be9720515b225

test:
  secret_key_base: 946433d3b68197f8db05914ba1ac154c52593384e7788f2aae685c4df58121c6b6d5fa744722c936cbeaac5219e2e31fbe2b4defe083889211379177f43a87c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
